In [7]:
import os
import pandas as pd
import snowflake.connector
from dotenv import load_dotenv

load_dotenv()
conn = snowflake.connector.connect(
    user=os.getenv("SNOWFLAKE_USER"),
    password=os.getenv("SNOWFLAKE_PASSWORD"),
    account=os.getenv("SNOWFLAKE_ACCOUNT"),
    warehouse=os.getenv("SNOWFLAKE_WAREHOUSE"),
    database=os.getenv("SNOWFLAKE_DATABASE"),
    role=os.getenv("SNOWFLAKE_ROLE"),
)
df = conn.cursor().execute("select * from raw.flights").fetch_pandas_all()
df.columns = df.columns.str.lower()

In [8]:
df.head(10)

,flight_id,departure_airport_swedish,departure_airport_english,di_indicator,flight_leg_identifier__callsign,flight_leg_identifier__flight_id,flight_leg_identifier__flight_departure_date_utc,flight_leg_identifier__departure_airport_iata,flight_leg_identifier__arrival_airport_iata,flight_leg_identifier__departure_airport_icao,...,location_and_status__gate_action_swedish,location_and_status__gate_action_english,location_and_status__gate_open_utc,location_and_status__gate_close_utc,departure_time__actual_utc,departure_time__estimated_utc,baggage__estimated_first_bag_utc,direction,query_date,fetched_at
0,FR915,Rom FCO,Rome FCO,S,RYR97XH,FR915,2026-10-06 17:00:00-07:00,FCO,ARN,LIRF,...,NaN,NaN,NaT,NaT,NaT,NaT,NaT,arrivals,2026-10-07,2026-10-09 01:16:01.402031-07:00
1,FR4464,Birmingham,Birmingham,I,RYR4464,FR4464,2026-10-06 17:00:00-07:00,BHX,ARN,EGBB,...,NaN,NaN,NaT,NaT,NaT,NaT,NaT,arrivals,2026-10-07,2026-10-09 01:16:01.402031-07:00
2,FR3008,Dublin,Dublin,I,RYR3008,FR3008,2026-10-06 17:00:00-07:00,DUB,ARN,EIDW,...,NaN,NaN,NaT,NaT,NaT,NaT,NaT,arrivals,2026-10-07,2026-10-09 01:16:01.402031-07:00
3,FR7619,Palma,Palma,S,RYR9JP,FR7619,2026-10-06 17:00:00-07:00,PMI,ARN,LEPA,...,NaN,NaN,NaT,NaT,NaT,NaT,NaT,arrivals,2026-10-07,2026-10-09 01:16:01.402031-07:00
4,FR7694,Chania,Chania,S,RYR7694,FR7694,2026-10-06 17:00:00-07:00,CHQ,ARN,LGSA,...,NaN,NaN,NaT,NaT,NaT,NaT,NaT,arrivals,2026-10-07,2026-10-09 01:16:01.402031-07:00
5,FR9447,Manchester,Manchester,I,RYR9447,FR9447,2026-10-06 17:00:00-07:00,MAN,ARN,EGCC,...,NaN,NaN,NaT,NaT,NaT,NaT,NaT,arrivals,2026-10-07,2026-10-09 01:16:01.402031-07:00
6,DE4409,Frankfurt,Frankfurt,S,CFG4409,DE4409,2026-10-06 17:00:00-07:00,FRA,ARN,EDDF,...,NaN,NaN,NaT,NaT,NaT,NaT,NaT,arrivals,2026-10-07,2026-10-09 01:16:01.402031-07:00
7,DE4405,Frankfurt,Frankfurt,S,CFG4405,DE4405,2026-10-06 17:00:00-07:00,FRA,ARN,EDDF,...,NaN,NaN,NaT,NaT,NaT,NaT,NaT,arrivals,2026-10-07,2026-10-09 01:16:01.402031-07:00
8,DE4403,Frankfurt,Frankfurt,S,CFG4403,DE4403,2026-10-06 17:00:00-07:00,FRA,ARN,EDDF,...,NaN,NaN,NaT,NaT,NaT,NaT,NaT,arrivals,2026-10-07,2026-10-09 01:16:01.402031-07:00
9,W62407,Budapest,Budapest,S,WZZ2407,W62407,2026-10-06 17:00:00-07:00,BUD,ARN,LHBP,...,NaN,NaN,NaT,NaT,NaT,NaT,NaT,arrivals,2026-10-07,2026-10-09 01:16:01.402031-07:00

In [13]:
df.shape

(3172, 48)

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3172 entries, 0 to 3171
Data columns (total 48 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   flight_id                                         3172 non-null   str
 1   departure_airport_swedish                         1591 non-null   str
 2   departure_airport_english                         1591 non-null   str
 3   di_indicator                                      3172 non-null   str
 4   flight_leg_identifier__callsign                   3172 non-null   str
 5   flight_leg_identifier__flight_id                  3172 non-null   str
 6   flight_leg_identifier__flight_departure_date_utc  3172 non-null   datetime64[ns, America/Los_Angeles]
 7   flight_leg_identifier__departure_airport_iata     3172 non-null   str
 8   flight_leg_identifier__arrival_airport_iata       3172 non-null   str
 9   flight_leg_identifier__departure_airport_icao     3172 non-null   str
 10  flight_leg_identifier__arrival_airport_icao       3172 non-null   str
 11  location_and_status__terminal                     3172 non-null   str
 12  location_and_status__flight_leg_status            3172 non-null   str
 13  location_and_status__flight_leg_status_swedish    3172 non-null   str
 14  location_and_status__flight_leg_status_english    3172 non-null   str
 15  arrival_time__scheduled_utc                       1591 non-null   datetime64[ns, America/Los_Angeles]
 16  airline_operator__iata                            3172 non-null   str
 17  airline_operator__icao                            3172 non-null   str
 18  airline_operator__name                            3172 non-null   str
 19  _dlt_load_id                                      3172 non-null   str
 20  _dlt_id                                           3172 non-null   str
 21  baggage__baggage_claim_unit                       1364 non-null   str
 22  flight_leg_identifier__aircraft_registration      2610 non-null   str
 23  flight_leg_identifier__ssr_code                   1736 non-null   str
 24  arrival_time__estimated_utc                       1312 non-null   datetime64[ns, America/Los_Angeles]
 25  baggage__first_bag_utc                            1207 non-null   datetime64[ns, America/Los_Angeles]
 26  baggage__last_bag_utc                             1196 non-null   datetime64[ns, America/Los_Angeles]
 27  location_and_status__gate                         2507 non-null   str
 28  arrival_time__actual_utc                          1303 non-null   datetime64[ns, America/Los_Angeles]
 29  arrival_airport_swedish                           1581 non-null   str
 30  arrival_airport_english                           1581 non-null   str
 31  departure_time__scheduled_utc                     1581 non-null   datetime64[ns, America/Los_Angeles]
 32  check_in__check_in_desk_from                      1250 non-null   float64
 33  check_in__check_in_desk_to                        1250 non-null   float64
 34  check_in__check_in_status                         1291 non-null   str
 35  check_in__check_in_status_swedish                 1291 non-null   str
 36  check_in__check_in_status_english                 1291 non-null   str
 37  location_and_status__gate_action                  1281 non-null   str
 38  location_and_status__gate_action_swedish          1263 non-null   str
 39  location_and_status__gate_action_english          1263 non-null   str
 40  location_and_status__gate_open_utc                1124 non-null   datetime64[ns, America/Los_Angeles]
 41  location_and_status__gate_close_utc               1283 non-null   datetime64[ns, America/Los_Angeles]
 42  departure_time__actual_utc                        1286 non-null   datetime64[ns, America/Los_Angeles]
 43  departure_time__estimated_utc                     145 non-null    datetime64[ns, America/Los_Angeles]
 44  baggage__estimated_first_bag_utc                  235 non-null    datetime64[ns, America/Los_Angeles]
 45  direction                                         3172 non-null   str
 46  query_date                                        3172 non-null   str
 47  fetched_at                                        3172 non-null   datetime64[ns, America/Los_Angeles]
dtypes: datetime64[ns, America/Los_Angeles](13), float64(2), str(33)
memory usage: 1.7 MB

In [15]:
df.columns

Index(['flight_id', 'departure_airport_swedish', 'departure_airport_english',
       'di_indicator', 'flight_leg_identifier__callsign',
       'flight_leg_identifier__flight_id',
       'flight_leg_identifier__flight_departure_date_utc',
       'flight_leg_identifier__departure_airport_iata',
       'flight_leg_identifier__arrival_airport_iata',
       'flight_leg_identifier__departure_airport_icao',
       'flight_leg_identifier__arrival_airport_icao',
       'location_and_status__terminal',
       'location_and_status__flight_leg_status',
       'location_and_status__flight_leg_status_swedish',
       'location_and_status__flight_leg_status_english',
       'arrival_time__scheduled_utc', 'airline_operator__iata',
       'airline_operator__icao', 'airline_operator__name', '_dlt_load_id',
       '_dlt_id', 'baggage__baggage_claim_unit',
       'flight_leg_identifier__aircraft_registration',
       'flight_leg_identifier__ssr_code', 'arrival_time__estimated_utc',
       'baggage__first_bag_utc', 'baggage__last_bag_utc',
       'location_and_status__gate', 'arrival_time__actual_utc',
       'arrival_airport_swedish', 'arrival_airport_english',
       'departure_time__scheduled_utc', 'check_in__check_in_desk_from',
       'check_in__check_in_desk_to', 'check_in__check_in_status',
       'check_in__check_in_status_swedish',
       'check_in__check_in_status_english', 'location_and_status__gate_action',
       'location_and_status__gate_action_swedish',
       'location_and_status__gate_action_english',
       'location_and_status__gate_open_utc',
       'location_and_status__gate_close_utc', 'departure_time__actual_utc',
       'departure_time__estimated_utc', 'baggage__estimated_first_bag_utc',
       'direction', 'query_date', 'fetched_at'],
      dtype='str')

In [16]:
df.isna().sum()

flight_id                                              0
departure_airport_swedish                           1581
departure_airport_english                           1581
di_indicator                                           0
flight_leg_identifier__callsign                        0
flight_leg_identifier__flight_id                       0
flight_leg_identifier__flight_departure_date_utc       0
flight_leg_identifier__departure_airport_iata          0
flight_leg_identifier__arrival_airport_iata            0
flight_leg_identifier__departure_airport_icao          0
flight_leg_identifier__arrival_airport_icao            0
location_and_status__terminal                          0
location_and_status__flight_leg_status                 0
location_and_status__flight_leg_status_swedish         0
location_and_status__flight_leg_status_english         0
arrival_time__scheduled_utc                         1581
airline_operator__iata                                 0
airline_operator__icao                                 0
airline_operator__name                                 0
_dlt_load_id                                           0
_dlt_id                                                0
baggage__baggage_claim_unit                         1808
flight_leg_identifier__aircraft_registration         562
flight_leg_identifier__ssr_code                     1436
arrival_time__estimated_utc                         1860
baggage__first_bag_utc                              1965
baggage__last_bag_utc                               1976
location_and_status__gate                            665
arrival_time__actual_utc                            1869
arrival_airport_swedish                             1591
arrival_airport_english                             1591
departure_time__scheduled_utc                       1591
check_in__check_in_desk_from                        1922
check_in__check_in_desk_to                          1922
check_in__check_in_status                           1881
check_in__check_in_status_swedish                   1881
check_in__check_in_status_english                   1881
location_and_status__gate_action                    1891
location_and_status__gate_action_swedish            1909
location_and_status__gate_action_english            1909
location_and_status__gate_open_utc                  2048
location_and_status__gate_close_utc                 1889
departure_time__actual_utc                          1886
departure_time__estimated_utc                       3027
baggage__estimated_first_bag_utc                    2937
direction                                              0
query_date                                             0
fetched_at                                             0
dtype: int64

In [17]:
df.fillna("missing")

,flight_id,departure_airport_swedish,departure_airport_english,di_indicator,flight_leg_identifier__callsign,flight_leg_identifier__flight_id,flight_leg_identifier__flight_departure_date_utc,flight_leg_identifier__departure_airport_iata,flight_leg_identifier__arrival_airport_iata,flight_leg_identifier__departure_airport_icao,...,location_and_status__gate_action_swedish,location_and_status__gate_action_english,location_and_status__gate_open_utc,location_and_status__gate_close_utc,departure_time__actual_utc,departure_time__estimated_utc,baggage__estimated_first_bag_utc,direction,query_date,fetched_at
0,FR915,Rom FCO,Rome FCO,S,RYR97XH,FR915,2026-10-06 17:00:00-07:00,FCO,ARN,LIRF,...,missing,missing,missing,missing,missing,missing,missing,arrivals,2026-10-07,2026-10-09 01:16:01.402031-07:00
1,FR4464,Birmingham,Birmingham,I,RYR4464,FR4464,2026-10-06 17:00:00-07:00,BHX,ARN,EGBB,...,missing,missing,missing,missing,missing,missing,missing,arrivals,2026-10-07,2026-10-09 01:16:01.402031-07:00
2,FR3008,Dublin,Dublin,I,RYR3008,FR3008,2026-10-06 17:00:00-07:00,DUB,ARN,EIDW,...,missing,missing,missing,missing,missing,missing,missing,arrivals,2026-10-07,2026-10-09 01:16:01.402031-07:00
3,FR7619,Palma,Palma,S,RYR9JP,FR7619,2026-10-06 17:00:00-07:00,PMI,ARN,LEPA,...,missing,missing,missing,missing,missing,missing,missing,arrivals,2026-10-07,2026-10-09 01:16:01.402031-07:00
4,FR7694,Chania,Chania,S,RYR7694,FR7694,2026-10-06 17:00:00-07:00,CHQ,ARN,LGSA,...,missing,missing,missing,missing,missing,missing,missing,arrivals,2026-10-07,2026-10-09 01:16:01.402031-07:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3167,SK1126,missing,missing,D,SAS1126,SK1126,2026-10-08 17:00:00-07:00,RNB,ARN,ESDF,...,Utgång stängd,Gate closed,2026-10-08 20:22:37-07:00,2026-10-08 20:31:15-07:00,2026-10-08 20:51:00-07:00,missing,missing,departures,2026-10-09,2026-10-10 02:02:07.862189-07:00
3168,SK1136,missing,missing,D,SAS1136,SK1136,2026-10-08 17:00:00-07:00,RNB,ARN,ESDF,...,Utgång stängd,Gate closed,2026-10-09 00:38:23-07:00,2026-10-09 01:07:55-07:00,2026-10-09 01:03:00-07:00,missing,missing,departures,2026-10-09,2026-10-10 02:02:07.862189-07:00
3169,SK1132,missing,missing,D,SAS1132,SK1132,2026-10-08 17:00:00-07:00,RNB,ARN,ESDF,...,Utgång stängd,Gate closed,2026-10-09 05:23:53-07:00,2026-10-09 05:47:23-07:00,2026-10-09 05:56:00-07:00,missing,missing,departures,2026-10-09,2026-10-10 02:02:07.862189-07:00
3170,SK1130,missing,missing,D,SAS1130,SK1130,2026-10-08 17:00:00-07:00,RNB,ARN,ESDF,...,Utgång stängd,Gate closed,2026-10-09 06:20:55-07:00,2026-10-09 06:38:55-07:00,2026-10-09 06:44:00-07:00,missing,missing,departures,2026-10-09,2026-10-10 02:02:07.862189-07:00
3171,SK1128,missing,missing,D,SAS1128,SK1128,2026-10-08 17:00:00-07:00,RNB,ARN,ESDF,...,Utgång stängd,Gate closed,2026-10-09 10:11:17-07:00,2026-10-09 10:34:59-07:00,2026-10-09 10:45:00-07:00,missing,missing,departures,2026-10-09,2026-10-10 02:02:07.862189-07:00

In [18]:
df.duplicated().sum()

np.int64(0)

In [23]:
df["flight_leg_identifier__callsign"].value_counts()

flight_leg_identifier__callsign
FRO671     9
FRO675     9
FRO679     9
FRO685     9
FRO670     9
          ..
WMT3210    1
WMT3212    1
VKG436     1
FT686      1
FIN312     1
Name: count, Length: 1243, dtype: int64